spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/db?user=app&password=pass}

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

